InitImageYoimiya:
  dreambooth_path: "models/DreamBooth_LoRA/AnythingV5_v5PrtRE.safetensors"
  init_image: "assets/yoimiya-init.jpg"

  lora_configs:
    - path: "models/DreamBooth_LoRA/genshin_impact_yoimiya.safetensors"
      alpha: 0.8
    - path: "models/DreamBooth_LoRA/LineLine2D.safetensors"
      alpha: 0.7

  motion_module:
    - "models/Motion_Module/mm_sd_v15_v2.ckpt"
  
  motion_module_lora_configs:
    - path:  "models/MotionLoRA/v2_lora_ZoomIn.ckpt"
      alpha: 1.0

  steps:          25
  guidance_scale: 7.5

  prompt:
    - "1girl, yoimiya (genshin impact), origen, line, comet, wink, Masterpiece ，BestQuality ，UltraDetailed"
    - "1girl, yoimiya (genshin impact), origen, line, formal, abstract, looking at viewer, Masterpiece ，BestQuality ，UltraDetailed"

  n_prompt:
    - "NSFW, lr, nsfw,(sketch, duplicate, ugly, huge eyes, text, logo, monochrome, worst face, (bad and mutated hands:1.3), (worst quality:2.0), (low quality:2.0), (blurry:2.0), horror, geometry, bad_prompt_v2, (bad hands), (missing fingers), multiple limbs, bad anatomy, (interlocked fingers:1.2), Ugly Fingers, (extra digit and hands and fingers and legs and arms:1.4), crown braid, ((2girl)), (deformed fingers:1.2), (long fingers:1.2),succubus wings,horn,succubus horn,succubus hairstyle, (bad-artist-anime), bad-artist, bad hand, grayscale, skin spots, acnes, skin blemishes"
    - "NSFW, lr, nsfw,(sketch, duplicate, ugly, huge eyes, text, logo, monochrome, worst face, (bad and mutated hands:1.3), (worst quality:2.0), (low quality:2.0), (blurry:2.0), horror, geometry, bad_prompt_v2, (bad hands), (missing fingers), multiple limbs, bad anatomy, (interlocked fingers:1.2), Ugly Fingers, (extra digit and hands and fingers and legs and arms:1.4), crown braid, ((2girl)), (deformed fingers:1.2), (long fingers:1.2),succubus wings,horn,succubus horn,succubus hairstyle, (bad-artist-anime), bad-artist, bad hand, grayscale, skin spots, acnes, skin blemishes"
  